### ISSUE TITLE
Ask for the CBF_Quadrotor folder

### ISSUE THREAD

**Issue by tangjuju** [Kvello/RL_CBF#1]
Hi, I am interested in your project, but I can't find the folder named CBF_Quadrotor, may I ask for it? Thanks

**Comment by Kvello** [comment]
Hi. This is unfortunately code that has not been publicly published yet. It is part of research not yet published at the ARL lab at NTNU. I assume it will be made public in the future. In any case, I will likely be making a new version of this library next year.
